### ISSUE TITLE
Input redstone direction bug

### ISSUE THREAD

**Issue by GoodClover** [Sciman101/minefuck#1]
This video illustrates the issue well:
https://www.youtube.com/watch?v=WLRaAr3qzsg

The code in the book (`+[,.+]`) is just an infinite loop that repeats the input to the output.

It appears that redstone input is only detected on the input if the redstone would point towards the interpreter directly.
The automatic connection that happens seems to not actually connect properly, meaning that the interpreter thinks the redstone isn't connected.

**Comment by GoodClover** [comment]
![2021-03-17_17 36 59](https://user-images.githubusercontent.com/27222523/111512243-72992900-8747-11eb-87f0-557fe12918b3.png)

My guess is minef*ck treats it like this:

![2021-03-17_17 37 03](https://user-images.githubusercontent.com/27222523/111512248-74fb8300-8747-11eb-8f12-7522436d133b.png)

**Comment by Sciman101** [comment]
I just pushed a [new build](https://modrinth.com/mod/minefck/version/AU5Owche) on Modrinth, looks like the issue was I was testing for emitted power rather than received power. Let me know if that works.

**Comment by GoodClover** [comment]
That appears to have partially fixed it.

![image](https://user-images.githubusercontent.com/27222523/111547740-86f21b80-8771-11eb-9b1c-22032f9bb473.png)

I also tested with all other mods removed and the same issue occurs.

**Comment by Sciman101** [comment]
Weird - the redstone methods are kind of hard to figure out, I _think_ this time it should work. [Pushed another version to Modrinth](https://modrinth.com/mod/minefck/version/w2zAxfmU), let me know if it helps!

**Comment by GoodClover** [comment]
Sorry for not replying earlier, this appears to have completely fixed it!

**Comment by Sciman101** [comment]
Great, good to hear! Thanks for letting me know
